name: CB-CI-ACTIONS-TRAGET-WORKFLOW

on:
  push:
  pull_request_target:

jobs:
  cb-ci-actions-target-job:
    name: CB-CI-ACTIONS-TARGET-JOB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13"]
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo 'workflow starting'

      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout Master
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Setup golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
          golangci-lint --version

      - name: Run Lint
        run: |
          golangci-lint run --config ./.github/.golangci.yaml | tee ./lint-result.xml

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Publish Lint Results
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ./lint-result.xml | reviewdog -f=checkstyle -name="Lint Results" -reporter=github-check
