name: CB-CI-ACTIONS-WORKFLOW

on:
  push:
  pull_request:

jobs:
  cb-ci-env-job:
    name: CB-CI-ENV-JOB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13"]
    steps:
      - name: Check Environment variable
        id: cev
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            (async _ => {
              const { GITHUB_CONTEXT } = process.env
              console.log('github', GITHUB_CONTEXT)
              console.log('context', context)       
              core.setOutput('branch', context.ref.replace("refs/heads/", ""))

              var author_association = ""
              console.log("context.actor", context.actor)
              console.log("owner.login", context.payload.repository.owner.login)
              if(context.actor == context.payload.repository.owner.login) author_association = "OWNER"
              if(author_association == "") {        
                try {
                  res = await github.orgs.listMembers({org: "cloud-barista" })
                  console.log('listMembers', res)
                  if (res.status >= 200 && res.status < 300) {
                    isMember = res.data.some(({ login }) => login === context.actor)
                    if(isMember) author_association = "MEMBER"
                  }                  
                } catch (e) {
                  console.log(e)
                }              
              }
              if(author_association == "") {        
                try {
                  res = await github.repos.listCollaborators({
                    owner: context.payload.repository.owner.login,
                    repo: context.payload.repository.name,
                  })
                  console.log('listCollaborators', res)
                  if (res.status >= 200 && res.status < 300) {
                    isCollaborator = res.data.some(({ login }) => login === context.actor)
                    if(isCollaborator) author_association = "COLLABORATOR"
                  }                   
                } catch (e) {
                  console.log(e)
                }            
              }              
              core.setOutput('author_association', author_association)

            })();

      - name: Display cev
        run: |
          echo "branch: ${{ steps.cev.outputs.branch }}"
          echo "author_association: ${{ steps.cev.outputs.author_association }}"
