name: CB-CI-ACTIONS

on:
  push:
  pull_request:

jobs:
  cb-ci-test:
    name: CB-CI-TEST
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13"]
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "workflow starting..."
          pwd
          ls

      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Save PR number
        run: |
          mkdir -p ./outputs
          echo ${{ github.event.number }} > ./outputs/pr_number.txt
          echo "Test1 PR is ${{ github.event.number }}"

      - name: PR Number
        id: findPr
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context)
            console.log("eventName", context.eventName)
            if(context.eventName == 'pull_request') {
              console.log("number1", context.number)
              core.setOutput('pr', context.number)
            }
            else if(context.eventName == 'push') {
              const result = await github.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha
              })
              console.log(result)

              const pr = result.data.length > 0 && result.data[0];
              core.setOutput('pr', pr && pr.number || '');     
              console.log("number2", pr.number)         
            }
            else {
              core.setOutput('pr', '')
            }

      - run: echo "Test2 PR is ${PR}"
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      - name: Run Test
        run: |
          go get gotest.tools/gotestsum
          gotestsum --junitfile ./outputs/unit-tests.xml

      - name: Upload Test Result
        uses: actions/upload-artifact@v2
        with:
          name: cb-artifact
          path: outputs/
