name: CB-CI-ACTIONS-WORKFLOW

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cb-ci-actions-job:
    name: CB-CI-ACTIONS-JOB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13"]
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
