name: CB-CI-ACTIONS

on:
  push:
  pull_request:

jobs:
  cb-ci-test:
    name: CB-CI-TEST
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13"]
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "workflow starting..."
          pwd
          ls

      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run Test
        run: |
          go get gotest.tools/gotestsum
          gotestsum --junitfile unit-tests.xml

      - name: Upload Test Result
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: unit-tests.xml
