name: CB-CI-ACTIONS-WORKFLOW

on:
  push:
  pull_request:

jobs:
  cb-ci-actions-job:
    name: CB-CI-ACTIONS-JOB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13"]
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "workflow starting..."
          pwd
          ls

      - name: Make Output Folder
        run: |
          mkdir -p ./outputs

      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Setup golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
          golangci-lint --version

      - name: Find PR Number
        id: findPrNumber
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if(context.eventName == 'pull_request') {
              core.setOutput('pr', context.payload.number)
            } else if(context.eventName == 'push') {
              const result = await github.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha
              })
              const pr = result.data.length > 0 && result.data[0];
              core.setOutput('pr', pr && pr.number || '');     
            } else {
              core.setOutput('pr', '')
            }

      - name: Save PR number
        env:
          PR: ${{ steps.findPrNumber.outputs.pr }}
        run: |
          ls -al
          echo ${PR} > ./outputs/pr_number.txt
          ls -al ./outputs

      - name: Run Lint
        run: |
          golangci-lint run --config ./.github/.golangci.yaml | tee ./outputs/lint-result.xml

      - name: Run Test
        run: |
          go get gotest.tools/gotestsum
          gotestsum --junitfile ./outputs/unit-tests.xml

      - name: Upload Result
        uses: actions/upload-artifact@v2
        with:
          name: cb-artifact
          path: outputs/
