name: CB-CI-ACTIONS-WORKFLOW

on:
  push:
  #pull_request:
  pull_request_target:

jobs:
  cb-ci-actions-job:
    name: CB-CI-ACTIONS-JOB
    #if: ${{ github.event_name != 'pull_request_target' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13"]
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo 'workflow starting'

      - uses: actions/checkout@v2

      - name: Make Output Folder
        run: |
          mkdir -p ./outputs

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Setup golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
          golangci-lint --version

      - name: Run Lint
        run: |
          golangci-lint run --config ./.github/.golangci.yaml | tee ./outputs/lint-result.xml

      - name: Run Test
        run: |
          go get gotest.tools/gotestsum
          gotestsum --junitfile ./outputs/unit-tests.xml

      - name: Upload Result
        uses: actions/upload-artifact@v2
        with:
          name: cb-artifact
          path: outputs/

  cb-ci-reports-job:
    name: CB-CI-REPORTS-JOB
    #if: ${{ github.event_name != 'pull_request' }}
    needs: cb-ci-actions-job
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "workflow starting..."

      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout Master
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ./cb-artifact/unit-tests.xml
