name: CB-CI-ACTIONS-WORKFLOW

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cb-ci-env-job:
    name: CB-CI-ENV-JOB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13"]
    steps:
      - name: Check Environment variable
        id: cev
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            (async _ => {
              const { GITHUB_CONTEXT } = process.env
              console.log('github', GITHUB_CONTEXT)
              var github = JSON.parse(GITHUB_CONTEXT)
              console.log('github.ref', github.ref)

              console.log('context', context)       

              var branch = ""
              if(context.eventName == "pull_request") branch = context.payload.pull_request.base.ref
              else if(context.eventName == "push") branch = context.ref.replace("refs/heads/", "")
              else if(context.eventName == "schedule") branch = context.ref.replace("refs/heads/", "")
              console.log('branch', branch)
              core.setOutput('branch', branch)

              var author_association = ""

              actor = ""
              owner = ""
              repoName = ""

              if(context.eventName == "schedule") {
                actor = context.actor
                owner = github.repository_owner
                repoName = github.repository.replace(actor+"/", "")
              } else {
                actor = context.actor
                owner = context.payload.repository.owner.login
                repoName = context.payload.repository.name
              }

              console.log('actor', actor)
              console.log('owner', owner)
              console.log('repoName', repoName)

              if(actor == owner) author_association = "OWNER"
              if(author_association == "") {        
                try {
                  res = await github.orgs.listMembers({org: "cloud-barista" })
                  console.log('listMembers', res)
                  if (res.status >= 200 && res.status < 300) {
                    isMember = res.data.some(({ login }) => login === actor)
                    if(isMember) author_association = "MEMBER"
                  }                  
                } catch (e) {
                  console.log(e)
                }              
              }
              if(author_association == "") {        
                try {
                  res = await github.repos.listCollaborators({
                    owner: owner,
                    repo: repoName,
                  })
                  console.log('listCollaborators', res)
                  if (res.status >= 200 && res.status < 300) {
                    isCollaborator = res.data.some(({ login }) => login === context.actor)
                    if(isCollaborator) author_association = "COLLABORATOR"
                  }                   
                } catch (e) {
                  console.log(e)
                }            
              }              
              core.setOutput('author_association', author_association)

              var skip_lint = false
              var title = ""
              if(context.eventName == "pull_request") title = context.payload.pull_request.title
              else if(context.eventName == "push") title = context.payload.head_commit.message
              else if(context.eventName == "schedule") title = ""
              if( title.includes('[skip lint]')) skip_lint = true
              console.log('title', title)
              console.log('skip_lint', skip_lint)
              core.setOutput('skip_lint', skip_lint)              

            })();

      - name: Display cev
        run: |
          echo "branch: ${{ steps.cev.outputs.branch }}"
          echo "author_association: ${{ steps.cev.outputs.author_association }}"
          echo "skip_lint: ${{ steps.cev.outputs.skip_lint }}"
