name: CB-CI-REPORTS

on:
  workflow_run:
    workflows: ["CB-CI-ACTIONS"]
    types:
      - completed

jobs:
  cb-ci-report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Result
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Display structure of downloaded files
        run: ls -R
