name: Go

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          GITHUB_EVNET: ${{ toJSON(github.event) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "workflow starting..."

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
