name: test1111

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cb-ci-actions-job:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
