name: CB-CI-ACTIONS-WORKFLOW

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cb-ci-actions-job:
    name: CB-CI-ACTIONS-JOB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13"]
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
