name: Go

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "workflow starting..."

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      # - name: Check out code into the Go module directory
      #   uses: actions/checkout@v2

      # - name: Check Folder1
      #   run: |
      #     pwd
      #     ls

      - name: Checkout PR
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ steps.findPr.outputs.pr }}
      #     pr: ${{ github.event.number }}

      - name: Check Folder2
        run: |
          pwd
          ls

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
