name: Go

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "workflow starting..."

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        if: github.event_name == 'push'
        uses: actions/checkout@v2

      - name: Check Folder1
        run: |
          pwd
          ls

      - name: Checkout PR
        if: github.event_name == 'pull_request_target'
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.number }}

      - name: Check Folder2
        run: |
          pwd
          ls

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
